name: Build and Publish
on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  SECRETS: ${{ toJSON(secrets) }}

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: journeyapps-platform/ci-actions
          token: ${{ secrets.GH_SHARED_TOKEN_2 }}
          path: .github/ci
          ref: v1
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 12.17
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.32.3
      - name: Authenticate
        run: |
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: PNPM install
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Publish Dev Dependencies
        run: | 
          GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
          lerna version 0.0.0-dev.$GIT_HASH --no-private --exact --force-publish --no-push --no-git-tag-version --yes
          lerna publish from-package --yes --npm-tag next --no-git-reset --ignore-scripts --no-verify-access
        if: ${{ github.ref != 'refs/heads/master' }}
      - name: Publish Dependencies
        run: lerna publish from-package --yes --ignore-scripts --no-verify-access
        if: ${{ github.ref == 'refs/heads/master' }}


         
      