name: Build and Publish
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Set the correct Node version using nvm
        shell: bash -l {0} 
        run: nvm install
      - name: Install Dependencies
        run: yarn install
      - name: Authenticate
        run: |
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: publish
        run: yarn run publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      