name: Build and Publish
on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  SECRETS: ${{ toJSON(secrets) }}

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: journeyapps-platform/ci-actions
          token: ${{ secrets.GH_SHARED_TOKEN_2 }}
          path: .github/ci
          ref: v1
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8

      - name: PNPM install
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Authenticate
        run: |
          echo "registry=https://registry.npmjs.org/" >> $HOME/.npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> $HOME/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish Dev Dependencies
        if: ${{ github.ref != 'refs/heads/master' }
        run: |
          pnpm changeset version --no-git-tag --snapshot dev
          pnpm changeset publish --tag next

      - name: Create Release Pull Request or Publish to npm
        if: ${{ github.ref == 'refs/heads/master' }}
        id: changesets
        uses: changesets/action@v1.4.1
        with:
          version: pnpm ci:version
          commit: "chore: update versions"
          title: "[Chore] update versions"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish production packages.
        if: ${{ github.ref == 'refs/heads/master' && steps.changesets.outputs.hasChangesets == 'false' && success() }}
        run: |
          pnpm ci:publish
