name: Build and Publish
on:
  push:
    branches:
      - release

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Set the correct Node version using nvm
        shell: bash -l {0} 
        run: nvm install
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn run build
      - name: publish
        run: yarn run dev-publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      