name: Test
on:
  pull_request:
    branches: [ master, release ]

env:
  SECRETS: ${{ toJSON(secrets) }}
  GITHUB_TOKEN: ${{ secrets.GH_SHARED_TOKEN_2 }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - uses: actions/checkout@v2
        with:
          repository: journeyapps-platform/ci-actions
          token: ${{ secrets.SHARED_GH_TOKEN }}
          path: .github/ci
          ref: v1

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 18.16.0

      - name: Install PNPM
        run: npm i pnpm@8 -g

      - name: Install Dependencies
        uses: ./.github/ci/actions/npm-install
        with:
          client: pnpm

      - name: Install Dependencies
        run: pnpm install
      - uses: browser-actions/setup-chrome@latest
      - name: Check Chrome
        run: chrome --version
      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: pnpm test