name: Test
on:
  pull_request:
    branches: [ master, release ]

env:
  SECRETS: ${{ toJSON(secrets) }}
  GITHUB_TOKEN: ${{ secrets.GH_SHARED_TOKEN_2 }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8

      - name: Authenticate
        run: |
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          pnpm whoami

      - name: Install Dependencies
        run: pnpm install
      - uses: browser-actions/setup-chrome@latest
      - name: Check Chrome
        run: chrome --version
      - uses: browser-actions/setup-firefox@latest
      - name: Check Firefox
        run: firefox --version
      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: pnpm test