
name: Test

on:
  pull_request:
    branches: [ master, release ]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Set the correct Node version using nvm
        shell: bash -l {0} 
        run: nvm install
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.0.2
      - name: Authenticate
        run: |
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          pnpm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Install Dependencies
        run: pnpm install
      - uses: browser-actions/setup-chrome@latest
      - name: Check Chrome
        run: chrome --version
      - name: Test
        run: pnpm test